-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 14:28:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema control_inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_inventario` DEFAULT CHARACTER SET utf8 ;
USE `control_inventario` ;

-- -----------------------------------------------------
-- Table `control_inventario`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `cif` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_UNIQUE` (`email` ASC)  ,
  UNIQUE INDEX `cif_UNIQUE` (`cif` ASC)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `internal_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `cif` VARCHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `phone` INT(9) NOT NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_empresa_cuenta1_idx` (`company_id` ASC)  ,
  UNIQUE INDEX `cif_UNIQUE` (`cif` ASC)  ,
  CONSTRAINT `fk_empresa_cuenta1`
    FOREIGN KEY (`company_id`)
    REFERENCES `control_inventario`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`office` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(9) NOT NULL,
  `customer_id` INT NOT NULL,
  `hours` TEXT NULL,
  `notes` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oficina_empresa1_idx` (`customer_id` ASC)  ,
  CONSTRAINT `fk_oficina_empresa1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `control_inventario`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_device` INT NULL,
  `name` VARCHAR(250) NOT NULL,
  `office_id` INT NOT NULL,
  `category_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dispositivo_oficina1_idx` (`office_id` ASC)  ,
  INDEX `fk_device_category1_idx` (`category_id` ASC)  ,
  CONSTRAINT `fk_dispositivo_oficina1`
    FOREIGN KEY (`office_id`)
    REFERENCES `control_inventario`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `control_inventario`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`device_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`device_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_nombre_dispositivo_y_periferico_categorias_idx` (`category_id` ASC)  ,
  CONSTRAINT `fk_nombre_dispositivo_y_periferico_categorias`
    FOREIGN KEY (`category_id`)
    REFERENCES `control_inventario`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `device_id` INT NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`, `device_id`),
  INDEX `fk_attribute_device1_idx` (`device_id` ASC)  ,
  CONSTRAINT `fk_attribute_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `control_inventario`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`setting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NOT NULL,
  `device_id` INT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `edition_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_configuracion_dispositivo1_idx` (`device_id` ASC)  ,
  CONSTRAINT `fk_configuracion_dispositivo1`
    FOREIGN KEY (`device_id`)
    REFERENCES `control_inventario`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`performance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `device_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_configuracion_dispositivo1_idx` (`device_id` ASC)  ,
  CONSTRAINT `fk_configuracion_dispositivo10`
    FOREIGN KEY (`device_id`)
    REFERENCES `control_inventario`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(9) NULL,
  `phone` INT(9) NOT NULL,
  `company_id` INT NOT NULL,
  `role` TINYINT(1) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `authkey` VARCHAR(250) NULL,
  `accessToken` VARCHAR(250) NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_cuenta1_idx` (`company_id` ASC)  ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC)  ,
  UNIQUE INDEX `mail_UNIQUE` (`email` ASC)  ,
  CONSTRAINT `fk_usuario_cuenta1`
    FOREIGN KEY (`company_id`)
    REFERENCES `control_inventario`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`office_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`office_assignment` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `office_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `office_id`),
  INDEX `fk_usuario_has_empresa_usuario1_idx` (`user_id` ASC)  ,
  INDEX `fk_asignacion_oficina_oficina1_idx` (`office_id` ASC)  ,
  CONSTRAINT `fk_usuario_has_empresa_usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `control_inventario`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_oficina_oficina1`
    FOREIGN KEY (`office_id`)
    REFERENCES `control_inventario`.`office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control_inventario`.`user_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_inventario`.`user_performance` (
  `user_id` INT NOT NULL,
  `performance_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `performance_id`),
  INDEX `fk_usuario_has_actuaciones_actuaciones1_idx` (`performance_id` ASC)  ,
  INDEX `fk_usuario_has_actuaciones_usuario1_idx` (`user_id` ASC)  ,
  CONSTRAINT `fk_usuario_has_actuaciones_usuario1`
    FOREIGN KEY (`user_id`)
    REFERENCES `control_inventario`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_actuaciones_actuaciones1`
    FOREIGN KEY (`performance_id`)
    REFERENCES `control_inventario`.`performance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

/** Inserciones en Base de datos*/

/********* Categorioas *****/

INSERT INTO category (name) VALUES ('Categoría 1');
INSERT INTO category (name) VALUES ('Categoría 2');
INSERT INTO category (name) VALUES ('Categoría 3');
INSERT INTO category (name) VALUES ('Categoría 4');
INSERT INTO category (name) VALUES ('Categoría 5');

/* EMPRESAS */

INSERT INTO company (email, name, cif) VALUES ('company1@ejemplo.com', 'company 1', 'CIF1');
INSERT INTO company (email, name, cif) VALUES ('company2@ejemplo.com', 'company 2', 'CIF2');
INSERT INTO company (email, name, cif) VALUES ('company3@ejemplo.com', 'company 3', 'CIF3');
INSERT INTO company (email, name, cif) VALUES ('company4@ejemplo.com', 'company 4', 'CIF4');
INSERT INTO company (email, name, cif) VALUES ('company5@ejemplo.com', 'company 5', 'CIF5');

/* CLIENTES */

INSERT INTO customer (internal_code, name, cif, company_id,phone) VALUES ('CI1', 'customer 1', 'CIFC1', 1,658545875);
INSERT INTO customer (internal_code, name, cif, company_id,phone) VALUES ('CI2', 'customer 2', 'CIFC2', 2,658545875);
INSERT INTO customer (internal_code, name, cif, company_id,phone) VALUES ('CI3', 'customer 3', 'CIFC3', 3,658545875);
INSERT INTO customer (internal_code, name, cif, company_id,phone) VALUES ('CI4', 'customer 4', 'CIFC4', 4,658545875);
INSERT INTO customer (internal_code, name, cif, company_id,phone) VALUES ('CI5', 'customer 5', 'CI  FC5', 5,658545875);

/* OFICNIAS */
INSERT INTO office (name, address, postal_code, phone, customer_id) VALUES ('office 1', 'Calle 1', 'CP1', '111111111', 1);
INSERT INTO office (name, address, postal_code, phone, customer_id) VALUES ('office 2', 'Calle 2', 'CP2', '222222222', 2);
INSERT INTO office (name, address, postal_code, phone, customer_id) VALUES ('office 3', 'Calle 3', 'CP3', '333333333', 3);
INSERT INTO office (name, address, postal_code, phone, customer_id) VALUES ('office 4', 'Calle 4', 'CP4', '444444444', 4);
INSERT INTO office (name, address, postal_code, phone, customer_id) VALUES ('office 5', 'Calle 5', 'CP5', '555555555', 5);

/* DISPOSITIVOS */
INSERT INTO device (parent_device, name, office_id) VALUES (null, 'Descripción 1',  1);
INSERT INTO device (parent_device, name, office_id) VALUES (null, 'Descripción 2', 2);
INSERT INTO device (parent_device, name,  office_id) VALUES (null, 'Descripción 3', 3);
INSERT INTO device (parent_device, name, office_id) VALUES (null, 'Descripción 4', 4);
INSERT INTO device (parent_device, name, office_id) VALUES (null, 'Descripción 5', 5);

/* Atributos */
INSERT INTO attribute (name, device_id, description) VALUES ("name1", 1, 'description');
INSERT INTO attribute (name, device_id, description) VALUES ("name2", 2, 'description');
INSERT INTO attribute (name, device_id, description) VALUES ("name6", 3, 'description');
INSERT INTO attribute (name, device_id, description) VALUES ("name5", 4, 'description');
INSERT INTO attribute (name, device_id, description) VALUES ("name3", 5, 'description');

/** configuraciones **/
INSERT INTO setting (name, description, device_id, creation_date, edition_date) VALUES ('Configuración 1', 'Descripción de Configuración 1', 1, '2023-10-11 00:00:00', '2023-10-12 00:00:00');
INSERT INTO setting (name, description, device_id, creation_date, edition_date) VALUES ('Configuración 2', 'Descripción de Configuración 2', 2, '2023-10-11 00:00:00', '2023-10-12 00:00:00');
INSERT INTO setting (name, description, device_id, creation_date, edition_date) VALUES ('Configuración 3', 'Descripción de Configuración 3', 3, '2023-10-11 00:00:00', '2023-10-12 00:00:00');
INSERT INTO setting (name, description, device_id, creation_date, edition_date) VALUES ('Configuración 4', 'Descripción de Configuración 4', 4, '2023-10-11 00:00:00', '2023-10-12 00:00:00');
INSERT INTO setting (name, description, device_id, creation_date, edition_date) VALUES ('Configuración 5', 'Descripción de Configuración 5', 5, '2023-10-11 00:00:00', '2023-10-12 00:00:00');

/* Actuaciones */
INSERT INTO performance (description, device_id, date) VALUES ('Actuación 1', 1, '2023-10-11 00:00:00');
INSERT INTO performance (description, device_id, date) VALUES ('Actuación 2', 2, '2023-10-11 00:00:00');
INSERT INTO performance (description, device_id, date) VALUES ('Actuación 3', 3, '2023-10-11 00:00:00');
INSERT INTO performance (description, device_id, date) VALUES ('Actuación 4', 4, '2023-10-11 00:00:00');
INSERT INTO performance (description, device_id, date) VALUES ('Actuación 5', 5, '2023-10-11 00:00:00');

/*Usuarios las claves son 1234*/
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 1', 'Apellido 1', 'DNI1', 111111111, 1, '1','user1@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 2', 'Apellido 2', 'DNI2', 222222222, 2, '2','user2@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 3', 'Apellido 3', 'DNI3', 333333333, 3, '3','user3@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 4', 'Apellido 4', 'DNI4', 444444444, 4, '2','user4@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 5', 'Apellido 5', 'DNI5', 555555555, 5, '3','user5@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('user 5', 'Apellido 5', 'DNI6', 555555555, 5, '1','user6@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('pruebaadmin', 'Apellido 5', 'DNI7', 555555555, 5, '1','pruebaadmin@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('pruebatrabajdor', 'Apellido 5', 'DNI8', 555555555, 5, '2','pruebatrabajador@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');
INSERT INTO user (username, surname, dni, phone, company_id, role, email, password	) VALUES ('pruebacliente', 'Apellido 5', 'DNI9', 555555555, 5, '3','preubacliente@1.com', '$2y$13$VlqY5H/MAJ1BSorFtTG29u42aO6pX0gBZ7e/i9OgfbYP2UWDgJLYW');


/* User oficinas */
INSERT INTO office_assignment (user_id, office_id) VALUES (1, 1);
INSERT INTO office_assignment (user_id, office_id) VALUES (2, 2);
INSERT INTO office_assignment (user_id, office_id) VALUES (3, 3);
INSERT INTO office_assignment (user_id, office_id) VALUES (4, 4);
INSERT INTO office_assignment (user_id, office_id) VALUES (5, 5);

/* user actuaciones */
INSERT INTO user_performance (user_id, performance_id) VALUES (1, 1);
INSERT INTO user_performance (user_id, performance_id) VALUES (2, 2);
INSERT INTO user_performance (user_id, performance_id) VALUES (3, 3);
INSERT INTO user_performance (user_id, performance_id) VALUES (4, 4);
INSERT INTO user_performance (user_id, performance_id) VALUES (5, 5);
